export const mockRestaurants = [
  {
    id: 1,
    name: "Meghana Foods",
    cuisine: "Biryani, North Indian, Asian",
    rating: 4.4,
    deliveryTime: 38,
    costForTwo: 500,
    imageUrl: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/u5dyf5s86wao2x8ptitb",
  },
  {
    id: 2,
    name: "KFC",
    cuisine: "Burger, Fast Food",
    rating: 4.1,
    deliveryTime: 31,
    costForTwo: 400,
    imageUrl: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/lxywxy_KFC_1_1",
  },
  {
    id: 3,
    name: "Pizza Hut",
    cuisine: "Pizza, Fast Food",
    rating: 3.8,
    deliveryTime: 45,
    costForTwo: 600,
    imageUrl: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pizzahut_1_1",
  },
  {
    id: 4,
    name: "Burger King",
    cuisine: "Burger, American",
    rating: 4.2,
    deliveryTime: 25,
    costForTwo: 350,
    imageUrl: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/burgerking_1_1",
  },
  {
    id: 5,
    name: "Subway",
    cuisine: "Salads, Snacks, Healthy Food",
    rating: 4.3,
    deliveryTime: 20,
    costForTwo: 450,
    imageUrl: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/subway_1_1",
  },
];